### ISSUE TITLE
French encoding

### ISSUE THREAD

**Issue by amineAUPEC** [Zeex/deezer-export#1]
Hello
First of all, you're script works well and saved me many times. 

In Excel, French Character such as é, à .... are displayed incorrectly. 

There's multiple ways to force encoding in Excel 
But even I thought it's better to do it directly from the export-script :)

Here's an improvement that I made   : 

```
element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
element.setAttribute('href', 'data:text/plain;charset=utf-8,%EF%BB%BF' + encodeURIComponent(text));
```
Source : [imal hasaranga perera](https://stackoverflow.com/users/3380944/imal-hasaranga-perera)
Thanks :)

**Comment by benforeva** [comment]
This works great; even Korean characters are displaying properly.
