### ISSUE TITLE
Invalid CSV - Space after separator

### ISSUE THREAD

**Issue by Kdriscro** [Zeex/deezer-export#5]
Hello, I had issue using the CSV generated by the script in another application and noticed it was related to the space after each separator (,).

As now
`Title,Album,Artist`
`"atitle", "analbum", "anartist1, anartist2, anartistn"`

Should be
`Title,Album,Artist`
`"atitle","analbum","anartist1, anartist2, anartistn"`

https://github.com/Zeex/deezer-export/blob/f4c83e5cce413534aeeed292a9244d004333cf63/deezer-export.js#L80

**Comment by Zeex** [comment]
Done, thanks!
